#!/usr/bin/env bash
#
# One-shot setup: Omada Controller 6.2 + UniFi Network Application via Podman
# quadlets on AlmaLinux 10.x (EL10). Run as root on a fresh install.
#
# Architecture: ONE shared MongoDB container (unifi-db) serves both apps.
#   - AVX CPU:    mongo:8.0
#   - no AVX:     mongo:4.4 (last pre-AVX major; same pairing TP-Link ships
#                 for native installs)
#   Omada always runs mbentley/omada-controller:6.2 with MONGO_EXTERNAL=true.
#
# Idempotent: safe to re-run; credentials and data are always preserved.
# If the very first MongoDB init is interrupted, wipe /opt/unifi/db and
# re-run (the init script only executes against an empty db dir).
#
# Includes small-disk/eMMC hygiene: image prune after every auto-update,
# 2-kernel retention, capped journal, zram swap, dnf cache cleanup,
# ext4 root reserve trimmed to 1%, fstrim.timer enabled.
# Also installs the box's baseline package set and enables dnf-automatic
# with apply_updates=yes and reboot=when-needed.
# Adds a shadowsocks-rust server container (AEAD-2022, autogenerated key).
#
# Port map (host):
#   Omada:  8088/tcp mgmt HTTP, 8043/tcp mgmt HTTPS, 8844/tcp portal HTTPS
#           (moved off 8843 to avoid clashing with UniFi's guest portal),
#           19810+27001+29810/udp discovery, 29811-29817/tcp adoption/mgmt
#   UniFi:  8443/tcp UI, 8080/tcp inform, 3478/udp STUN, 10001/udp discovery
#   Shadowsocks: 8388/tcp + 8388/udp

set -euo pipefail

#--- Config -----------------------------------------------------------------
OMADA_DIR=/opt/omada
UNIFI_DIR=/opt/unifi
SS_DIR=/opt/shadowsocks
QUADLET_DIR=/etc/containers/systemd
CRED_FILE=${UNIFI_DIR}/credentials.env
OMADA_IMAGE=docker.io/mbentley/omada-controller:6.2
UNIFI_IMAGE=lscr.io/linuxserver/unifi-network-application:latest
SS_IMAGE=ghcr.io/shadowsocks/ssserver-rust:latest
SS_PORT=8388
# Low-memory defaults sized for the 2GB t240; raise on bigger hosts.
OMADA_HEAP_MAX=512m
OMADA_HEAP_MIN=128m
UNIFI_MEM_LIMIT=512
MONGO_CACHE_GB=0.25

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==> WARNING:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m==> ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ ${EUID} -eq 0 ]] || die "Run as root."

TZ_VAL=$(timedatectl show -p Timezone --value 2>/dev/null) || TZ_VAL=Etc/UTC
log "Timezone: ${TZ_VAL}"

#--- AVX check -> MongoDB tag (Omada is 6.2 either way) ---------------------
if grep -qw avx /proc/cpuinfo; then
  MONGO_TAG=8.0
  log "AVX present: shared MongoDB ${MONGO_TAG}"
else
  MONGO_TAG=4.4
  log "No AVX: shared MongoDB ${MONGO_TAG} (last pre-AVX major)"
fi

#--- Packages ---------------------------------------------------------------
log "Installing podman + baseline packages"
dnf -y install podman container-selinux openssl \
  dnf-automatic NetworkManager-wifi nano net-tools rsync udisks2 \
  vim-enhanced wget iperf3 bash-completion \
  pciutils usbutils >/dev/null

#--- Small-disk / eMMC hygiene ----------------------------------------------
log "Applying small-disk hygiene (kernel retention, journal cap, prune hook, zram)"

# Keep at most 2 installed kernels (default is 3)
if grep -q '^installonly_limit=' /etc/dnf/dnf.conf; then
  sed -i 's/^installonly_limit=.*/installonly_limit=2/' /etc/dnf/dnf.conf
else
  echo 'installonly_limit=2' >> /etc/dnf/dnf.conf
fi

# Cap the persistent journal; uncomment Storage=volatile instead once logs
# are shipped off-box (kinder to eMMC endurance)
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/10-small-disk.conf <<EOF
[Journal]
SystemMaxUse=100M
#Storage=volatile
EOF
systemctl restart systemd-journald

# Prune dangling images every time podman-auto-update runs so superseded
# image layers never accumulate after container updates
mkdir -p /etc/systemd/system/podman-auto-update.service.d
cat > /etc/systemd/system/podman-auto-update.service.d/10-prune.conf <<EOF
[Service]
ExecStartPost=/usr/bin/podman image prune -f
EOF

# zram swap instead of a disk swap partition (2GB RAM, eMMC endurance)
if dnf -y install zram-generator-defaults >/dev/null 2>&1; then
  systemctl daemon-reload
  systemctl start systemd-zram-setup@zram0.service 2>/dev/null \
    || warn "zram will activate on next boot"
else
  warn "zram-generator-defaults not available - skipping zram setup"
fi

# Reclaim most of ext4's default 5% root reserve; enable periodic TRIM
ROOT_DEV=$(findmnt -n -o SOURCE /)
if [[ $(findmnt -n -o FSTYPE /) == ext4 ]]; then
  tune2fs -m 1 "${ROOT_DEV}" >/dev/null
  log "ext4 root reserve set to 1% on ${ROOT_DEV}"
else
  warn "root is not ext4 - skipping tune2fs root-reserve trim"
fi
systemctl enable --now fstrim.timer >/dev/null 2>&1

dnf clean all >/dev/null

#--- Automatic OS updates (dnf-automatic) -----------------------------------
log "Configuring dnf-automatic (apply updates, reboot when needed)"
set_automatic() {
  # Set key = value under [commands], replacing an existing line or
  # inserting after the section header. Idempotent; preserves comments.
  local key=$1 val=$2 f=/etc/dnf/automatic.conf
  if grep -qE "^${key}[[:space:]]*=" "${f}"; then
    sed -i -E "s/^${key}[[:space:]]*=.*/${key} = ${val}/" "${f}"
  else
    sed -i "/^\[commands\]/a ${key} = ${val}" "${f}"
  fi
  grep -q "^${key} = ${val}$" "${f}" \
    || die "Could not set ${key} in ${f}"
}
set_automatic apply_updates yes
set_automatic reboot when-needed
systemctl enable --now dnf-automatic.timer >/dev/null 2>&1

#--- Directories ------------------------------------------------------------
mkdir -p "${OMADA_DIR}"/{data,logs} "${UNIFI_DIR}"/{config,db} "${SS_DIR}" "${QUADLET_DIR}"

#--- Credentials (generated once, reused on re-run) -------------------------
if [[ ! -f ${CRED_FILE} ]]; then
  log "Generating credentials -> ${CRED_FILE}"
  install -m 600 /dev/null "${CRED_FILE}"
  {
    echo "MONGO_ROOT_PASS=$(openssl rand -hex 24)"
    echo "MONGO_UNIFI_PASS=$(openssl rand -hex 24)"
    echo "MONGO_OMADA_PASS=$(openssl rand -hex 24)"
    echo "SS_PASSWORD=$(openssl rand -base64 32)"
  } > "${CRED_FILE}"
else
  log "Reusing credentials from ${CRED_FILE}"
fi
# SS_PASSWORD was added after the mongo passwords; append if absent
grep -q '^SS_PASSWORD=' "${CRED_FILE}" \
  || echo "SS_PASSWORD=$(openssl rand -base64 32)" >> "${CRED_FILE}"
# shellcheck source=/dev/null
source "${CRED_FILE}"
[[ -n ${MONGO_ROOT_PASS:-} && -n ${MONGO_UNIFI_PASS:-} && -n ${MONGO_OMADA_PASS:-} && -n ${SS_PASSWORD:-} ]] \
  || die "${CRED_FILE} is missing one of MONGO_ROOT_PASS / MONGO_UNIFI_PASS / MONGO_OMADA_PASS / SS_PASSWORD"

#--- Mongo first-run init script (runs only against an empty /data/db) ------
cat > "${UNIFI_DIR}/init-mongo.sh" <<'EOS'
#!/bin/bash
if which mongosh > /dev/null 2>&1; then
  mongo_init_bin='mongosh'
else
  mongo_init_bin='mongo'
fi
"${mongo_init_bin}" <<EOF
use ${MONGO_AUTHSOURCE}
db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
// unifi user lives in admin (app auths with MONGO_AUTHSOURCE=admin);
// created here in the current (admin) context, per upstream linuxserver.io
db.createUser({
  user: "${MONGO_USER}",
  pwd: "${MONGO_PASS}",
  roles: [
    { role: "dbOwner", db: "${MONGO_DBNAME}" },
    { role: "dbOwner", db: "${MONGO_DBNAME}_stat" },
    { role: "dbOwner", db: "${MONGO_DBNAME}_audit" }
  ]
})
// omada user lives in the omada db itself (its URI authSource is /omada);
// roles mirror mbentley's canonical omada.js: v6 uses omada AND omada_data
db.getSiblingDB("omada").createUser({
  user: "omada",
  pwd: "${MONGO_OMADA_PASS}",
  roles: [
    { role: "readWrite", db: "omada" },
    { role: "dbOwner",   db: "omada" },
    { role: "readWrite", db: "omada_data" },
    { role: "dbOwner",   db: "omada_data" }
  ]
})
EOF
EOS
chmod 755 "${UNIFI_DIR}/init-mongo.sh"

#--- Quadlet: shared network ------------------------------------------------
log "Writing ${QUADLET_DIR}/unifi.network"
cat > "${QUADLET_DIR}/unifi.network" <<EOF
# Shared by unifi-db, unifi, and omada
[Network]
NetworkName=unifi
EOF

#--- Quadlet: shared MongoDB ------------------------------------------------
log "Writing ${QUADLET_DIR}/unifi-db.container"
cat > "${QUADLET_DIR}/unifi-db.container" <<EOF
[Unit]
Description=Shared MongoDB (UniFi + Omada)

[Container]
Image=docker.io/mongo:${MONGO_TAG}
ContainerName=unifi-db
Network=unifi.network
Exec=--wiredTigerCacheSizeGB ${MONGO_CACHE_GB}
Volume=${UNIFI_DIR}/db:/data/db:Z
Volume=${UNIFI_DIR}/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro,Z
Environment=MONGO_INITDB_ROOT_USERNAME=root
Environment=MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
Environment=MONGO_USER=unifi
Environment=MONGO_PASS=${MONGO_UNIFI_PASS}
Environment=MONGO_DBNAME=unifi
Environment=MONGO_AUTHSOURCE=admin
Environment=MONGO_OMADA_PASS=${MONGO_OMADA_PASS}

[Service]
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
chmod 600 "${QUADLET_DIR}/unifi-db.container"

#--- Quadlet: Omada Controller 6.2 (external Mongo) -------------------------
log "Writing ${QUADLET_DIR}/omada.container"
cat > "${QUADLET_DIR}/omada.container" <<EOF
[Unit]
Description=Omada Controller (external MongoDB)
Requires=unifi-db.service
After=unifi-db.service

[Container]
Image=${OMADA_IMAGE}
AutoUpdate=registry
Network=unifi.network
Environment=TZ=${TZ_VAL}
Environment=MONGO_EXTERNAL=true
Environment=EAP_MONGOD_URI=mongodb://omada:${MONGO_OMADA_PASS}@unifi-db:27017/omada
Environment=PORTAL_HTTPS_PORT=8844
Environment=JAVA_MAX_HEAP_SIZE=${OMADA_HEAP_MAX}
Environment=JAVA_MIN_HEAP_SIZE=${OMADA_HEAP_MIN}
Volume=${OMADA_DIR}/data:/opt/tplink/EAPController/data:Z
Volume=${OMADA_DIR}/logs:/opt/tplink/EAPController/logs:Z
PublishPort=8088:8088
PublishPort=8043:8043
PublishPort=8844:8844
PublishPort=19810:19810/udp
PublishPort=27001:27001/udp
PublishPort=29810:29810/udp
PublishPort=29811-29817:29811-29817
PodmanArgs=--stop-timeout=60 --ulimit nofile=4096:8192

[Service]
Restart=on-failure
TimeoutStartSec=900
TimeoutStopSec=90

[Install]
WantedBy=multi-user.target
EOF
chmod 600 "${QUADLET_DIR}/omada.container"

#--- Quadlet: UniFi Network Application -------------------------------------
log "Writing ${QUADLET_DIR}/unifi.container"
cat > "${QUADLET_DIR}/unifi.container" <<EOF
[Unit]
Description=UniFi Network Application
Requires=unifi-db.service
After=unifi-db.service

[Container]
Image=${UNIFI_IMAGE}
AutoUpdate=registry
Network=unifi.network
Environment=PUID=1000
Environment=PGID=1000
Environment=TZ=${TZ_VAL}
Environment=MONGO_HOST=unifi-db
Environment=MONGO_PORT=27017
Environment=MONGO_USER=unifi
Environment=MONGO_PASS=${MONGO_UNIFI_PASS}
Environment=MONGO_DBNAME=unifi
Environment=MONGO_AUTHSOURCE=admin
Environment=MEM_LIMIT=${UNIFI_MEM_LIMIT}
Volume=${UNIFI_DIR}/config:/config:Z
PublishPort=8443:8443
PublishPort=8080:8080
PublishPort=3478:3478/udp
PublishPort=10001:10001/udp
PodmanArgs=--stop-timeout=60

[Service]
Restart=on-failure
TimeoutStartSec=900
TimeoutStopSec=90

[Install]
WantedBy=multi-user.target
EOF
chmod 600 "${QUADLET_DIR}/unifi.container"

#--- shadowsocks-rust: config + quadlet -------------------------------------
log "Writing ${SS_DIR}/config.json"
install -m 600 /dev/null "${SS_DIR}/config.json"
cat > "${SS_DIR}/config.json" <<EOF
{
    "server": "0.0.0.0",
    "server_port": ${SS_PORT},
    "method": "2022-blake3-aes-256-gcm",
    "password": "${SS_PASSWORD}",
    "mode": "tcp_and_udp"
}
EOF

log "Writing ${QUADLET_DIR}/shadowsocks.container"
cat > "${QUADLET_DIR}/shadowsocks.container" <<EOF
[Unit]
Description=shadowsocks-rust server

[Container]
Image=${SS_IMAGE}
ContainerName=shadowsocks
AutoUpdate=registry
Volume=${SS_DIR}/config.json:/etc/shadowsocks-rust/config.json:ro,Z
PublishPort=${SS_PORT}:${SS_PORT}
PublishPort=${SS_PORT}:${SS_PORT}/udp

[Service]
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

#--- Firewall ---------------------------------------------------------------
if systemctl is-active --quiet firewalld; then
  log "Opening firewalld ports"
  firewall-cmd -q --permanent --add-port={8043,8088,8443,8080,8844}/tcp
  firewall-cmd -q --permanent --add-port=29811-29817/tcp
  firewall-cmd -q --permanent --add-port={19810,27001,29810,3478,10001}/udp
  firewall-cmd -q --permanent --add-port="${SS_PORT}/tcp" --add-port="${SS_PORT}/udp"
  firewall-cmd -q --reload
else
  warn "firewalld not active - skipping firewall rules"
fi

#--- Pre-pull images --------------------------------------------------------
for img in "${OMADA_IMAGE}" "docker.io/mongo:${MONGO_TAG}" "${UNIFI_IMAGE}" "${SS_IMAGE}"; do
  log "Pulling ${img}"
  podman pull -q "${img}" >/dev/null
done

#--- Generate units and start -----------------------------------------------
log "Reloading systemd (quadlet generation)"
systemctl daemon-reload
for u in omada unifi-db unifi shadowsocks; do
  systemctl cat "${u}.service" >/dev/null 2>&1 \
    || die "Quadlet generation failed for ${u}.service. Debug with: /usr/lib/systemd/system-generators/podman-system-generator --dryrun"
done

# Stop-then-start (rather than plain start) so re-runs apply config changes
systemctl stop unifi.service omada.service shadowsocks.service unifi-db.service 2>/dev/null || true
systemctl start unifi-db.service

log "Waiting for MongoDB to answer"
t=0
until podman exec unifi-db sh -c \
  'command -v mongosh >/dev/null 2>&1 && exec mongosh --quiet --eval "db.adminCommand({ping:1}).ok" || exec mongo --quiet --eval "db.adminCommand({ping:1}).ok"' \
  >/dev/null 2>&1; do
  sleep 2; t=$(( t + 2 ))
  (( t >= 120 )) && die "MongoDB not answering after 120s. See: podman logs unifi-db"
done

log "Starting omada, unifi, and shadowsocks services"
systemctl start omada.service unifi.service shadowsocks.service

log "Enabling podman-auto-update.timer"
systemctl enable --now podman-auto-update.timer >/dev/null 2>&1

#--- Verify boot enablement -------------------------------------------------
# Quadlet units are enabled via their [Install] WantedBy at generation time;
# 'systemctl enable' does not apply to generated units.
for u in omada unifi-db unifi shadowsocks; do
  if [[ -e /run/systemd/generator/multi-user.target.wants/${u}.service ]]; then
    log "${u}.service: will start at boot (multi-user.target.wants)"
  else
    warn "${u}.service not linked into multi-user.target.wants - check its [Install] section"
  fi
done

#--- Verify runtime ---------------------------------------------------------
for u in omada unifi-db unifi shadowsocks; do
  systemctl is-active --quiet "${u}.service" \
    || die "${u}.service is not active. See: journalctl -eu ${u}.service"
done
log "All services active"

wait_for() {
  local name=$1 url=$2 timeout=${3:-420} t=0
  until curl -skf -o /dev/null --max-time 5 "${url}"; do
    t=$(( t + 5 ))
    if (( t >= timeout )); then
      warn "${name} not answering at ${url} after ${timeout}s (may still be initializing; check journalctl -eu)"
      return 0
    fi
    sleep 5
  done
  log "${name} is up: ${url}"
}

log "Waiting for web UIs (first boot on this hardware can take several minutes)..."
wait_for "UniFi" https://localhost:8443
wait_for "Omada" https://localhost:8043

#--- Summary ----------------------------------------------------------------
HOST_IP=$(hostname -I | awk '{print $1}')
cat <<EOF

============================================================
 Done.

 Omada 6.2        : https://${HOST_IP}:8043   (portal on 8844)
 UniFi Network    : https://${HOST_IP}:8443   (inform on 8080)
 Shared MongoDB   : mongo:${MONGO_TAG} in 'unifi-db' (dbs: unifi, omada)
 Shadowsocks      : ${HOST_IP}:${SS_PORT} tcp+udp, 2022-blake3-aes-256-gcm
                    (key = SS_PASSWORD in the credentials file)

 Credentials      : ${CRED_FILE} (mode 600)
 Quadlet units    : ${QUADLET_DIR}/{omada,unifi,unifi-db,shadowsocks}.container
 Data             : ${OMADA_DIR}, ${UNIFI_DIR}, ${SS_DIR}
 Auto-updates     : podman-auto-update.timer (omada 6.2.x + unifi + ss; mongo pinned)
 Disk hygiene     : image prune after auto-updates, installonly_limit=2,
                    journal capped at 100M, zram swap (no disk swap),
                    ext4 reserve at 1%, fstrim.timer on
 OS updates       : dnf-automatic daily (apply_updates=yes, reboot=when-needed)

 Both UIs run a first-time setup wizard. L3 adoption:
   UniFi devices : set-inform http://${HOST_IP}:8080/inform (or DHCP opt 43)
   Omada devices : controller IP ${HOST_IP} (or DHCP opt 138)
============================================================
EOF
