#!/usr/bin/env bash
#
# One-shot setup: Omada Controller 6.2 + UniFi Network Application via Podman
# quadlets on AlmaLinux 10.x (EL10). Run as root on a fresh install.
#
# Architecture: ONE shared MongoDB container (unifi-db) serves both apps.
#   - AVX CPU:    mongo:8.0
#   - no AVX:     mongo:4.4 (last pre-AVX major; the external-Mongo path
#                 mbentley documents for non-AVX hosts. 4.4 is EOL -
#                 accepted risk: LAN-only, never published to the host)
#   Omada always runs mbentley/omada-controller:6.2-openj9 (OpenJ9 JVM,
#   30-50% lower RSS than HotSpot - matters on 2GB) with MONGO_EXTERNAL=true.
#   All app images are PINNED: pulled once, never re-pulled or auto-updated.
#   To update deliberately: podman pull <image> && systemctl restart <svc>,
#   then podman image prune -f. Before updating unifi, confirm the new
#   version still supports MongoDB 4.4 (its mongo floor will rise one day).
#
# Adoption is L3-only: discovery broadcasts (10001/29810/udp) do not cross
# the podman bridge network. Use set-inform / controller IP / DHCP opt 43+138.
#
# Idempotent: safe to re-run; credentials and data are always preserved.
# If the very first MongoDB init is interrupted, wipe /opt/unifi/db and
# re-run (the init script only executes against an empty db dir).
#
# Includes small-disk/eMMC hygiene: superseded-image cleanup,
# 2-kernel retention, capped journal, zram swap, dnf cache cleanup,
# ext4 root reserve trimmed to 1%, fstrim.timer enabled.
# Also installs the box's baseline package set and enables dnf-automatic
# with apply_updates=yes and reboot=when-needed.
# Adds a shadowsocks-rust server container (AEAD-2022, autogenerated key).
# Adds a dnsmasq LAN resolver (native package, not a container; DNS only -
# no dhcp-range is ever configured, so its DHCP/TFTP engine stays off):
# hagezi pro blocklist refreshed daily, upstreams Cloudflare + Google over
# IPv4 and IPv6, and optional Steam steering at a local lancache with
# automatic fallback to the upstreams while the cache is unreachable.
#
# Component flags (default all-on) let another box run a subset - as
# arguments or env vars (arguments win), see --help:
#   ./setup-fedora-controllers.sh --no-unifi --no-shadowsocks
#   ENABLE_UNIFI=0 ENABLE_SHADOWSOCKS=0 ./setup-fedora-controllers.sh
# MongoDB (unifi-db) is provisioned whenever unifi or omada is enabled and
# looks identical either way (both app users always exist); with neither app
# enabled there is no MongoDB. Disabling a component on a re-run stops it
# and removes its quadlet; data dirs and images are kept for manual cleanup.
#
# Port map (host):
#   Omada:  8088/tcp mgmt HTTP, 8043/tcp mgmt HTTPS, 8844/tcp portal HTTPS
#           (moved off 8843 to avoid clashing with UniFi's guest portal),
#           19810+27001+29810/udp discovery, 29811-29817/tcp adoption/mgmt
#   UniFi:  8443/tcp UI, 8080/tcp inform, 3478/udp STUN, 10001/udp discovery
#   Shadowsocks: 8388/tcp + 8388/udp
#   DNS:    53/tcp + 53/udp

set -euo pipefail

#--- Config -----------------------------------------------------------------
# Component switches (0/1) - override from the environment
ENABLE_OMADA=${ENABLE_OMADA:-1}
ENABLE_UNIFI=${ENABLE_UNIFI:-1}
ENABLE_SHADOWSOCKS=${ENABLE_SHADOWSOCKS:-1}
ENABLE_DNS=${ENABLE_DNS:-1}
# Optional per-site: IPv4 of a local lancache; empty = no Steam steering
LANCACHE_IP=${LANCACHE_IP:-}
OMADA_DIR=/opt/omada
UNIFI_DIR=/opt/unifi
SS_DIR=/opt/shadowsocks
QUADLET_DIR=/etc/containers/systemd
# Holds every generated secret; same path on every box regardless of flags
CRED_FILE=${UNIFI_DIR}/credentials.env
OMADA_IMAGE=docker.io/mbentley/omada-controller:6.2-openj9
UNIFI_IMAGE=lscr.io/linuxserver/unifi-network-application:latest
SS_IMAGE=ghcr.io/shadowsocks/ssserver-rust:latest
SS_PORT=8388
# dnsmasq LAN DNS (DNS only - no DHCP)
HAGEZI_URL=https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/dnsmasq/pro.txt
HAGEZI_CONF=/etc/dnsmasq.d/hagezi-pro.conf
DNS_UPDATE_SCRIPT=/usr/local/sbin/update-hagezi-blocklist
LANCACHE_CONF=/etc/dnsmasq.d/lancache.conf
LANCACHE_TOGGLE=/usr/local/sbin/lancache-dns-toggle
# Low-memory defaults sized for the 2GB t240; raise on bigger hosts.
OMADA_HEAP_MAX=512m
OMADA_HEAP_MIN=128m
UNIFI_MEM_LIMIT=512
MONGO_CACHE_GB=0.25

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==> WARNING:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m==> ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: ${0##*/} [OPTIONS]

One-shot, idempotent setup of the Omada and UniFi controllers (backed by a
shared MongoDB) plus a shadowsocks-rust server, as Podman quadlets, and a
dnsmasq LAN DNS server (native, DNS only - no DHCP), with
small-disk/2GB-RAM host tuning. Run as root.

Options:
  --omada / --no-omada              enable/disable the Omada controller
  --unifi / --no-unifi              enable/disable the UniFi Network app
  --shadowsocks / --no-shadowsocks  enable/disable the shadowsocks server
  --dns / --no-dns                  enable/disable the dnsmasq LAN DNS server
                                    (hagezi pro blocklist, Cloudflare+Google
                                    upstreams over IPv4+IPv6)
  --lancache <ip> / --no-lancache   steer Steam downloads at a lancache on
                                    <ip>; auto-falls back to the upstreams
                                    while the cache is unreachable (needs dns)
  -h, --help                        show this help and exit

All components except lancache default to enabled. Each can also be set from
the environment (ENABLE_OMADA / ENABLE_UNIFI / ENABLE_SHADOWSOCKS /
ENABLE_DNS = 0|1, LANCACHE_IP=<ip>); arguments override the environment.
MongoDB (unifi-db) is provisioned automatically whenever omada or unifi is
enabled - and looks identical either way - but not at all otherwise.
Disabling a component on a re-run stops it and removes its quadlet/units;
data directories and images are kept for manual cleanup.

Examples:
  ${0##*/} --no-unifi --no-shadowsocks    # omada-only box
  ENABLE_UNIFI=0 ${0##*/}                 # same idea via the environment
  ${0##*/} --lancache 192.168.1.99        # the site with the Steam cache
EOF
}

while (( $# )); do
  case $1 in
    --omada)          ENABLE_OMADA=1 ;;
    --no-omada)       ENABLE_OMADA=0 ;;
    --unifi)          ENABLE_UNIFI=1 ;;
    --no-unifi)       ENABLE_UNIFI=0 ;;
    --shadowsocks)    ENABLE_SHADOWSOCKS=1 ;;
    --no-shadowsocks) ENABLE_SHADOWSOCKS=0 ;;
    --dns)            ENABLE_DNS=1 ;;
    --no-dns)         ENABLE_DNS=0 ;;
    --lancache)       LANCACHE_IP=${2:-}
                      [[ -n ${LANCACHE_IP} ]] || die "--lancache needs an IP argument"
                      shift ;;
    --no-lancache)    LANCACHE_IP= ;;
    -h|--help)        usage; exit 0 ;;
    *)                usage >&2; die "Unknown option: $1" ;;
  esac
  shift
done

[[ ${EUID} -eq 0 ]] || die "Run as root."

for flag in ENABLE_OMADA ENABLE_UNIFI ENABLE_SHADOWSOCKS ENABLE_DNS; do
  [[ ${!flag} =~ ^[01]$ ]] || die "${flag} must be 0 or 1 (got '${!flag}')"
done
if [[ -n ${LANCACHE_IP} ]]; then
  (( ENABLE_DNS )) || die "--lancache requires the dns component (drop --no-dns)"
  [[ ${LANCACHE_IP} =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] \
    || die "LANCACHE_IP must be an IPv4 address (got '${LANCACHE_IP}')"
fi
# The shared MongoDB exists to serve the controllers - either one pulls it in
ENABLE_MONGO=$(( ENABLE_OMADA || ENABLE_UNIFI ))
log "Components: omada=${ENABLE_OMADA} unifi=${ENABLE_UNIFI} mongodb=${ENABLE_MONGO} shadowsocks=${ENABLE_SHADOWSOCKS} dns=${ENABLE_DNS} lancache=${LANCACHE_IP:-off}"

# Preflight: image pulls need ~1.9GB; manual updates hold old+new layers
AVAIL_MB=$(df --output=avail -BM / | tail -1 | tr -dc '0-9')
if (( ENABLE_MONGO )); then
  (( AVAIL_MB >= 2048 )) \
    || die "Only ${AVAIL_MB}MB free on / - need at least 2GB for image pulls."
  (( AVAIL_MB >= 3584 )) \
    || warn "${AVAIL_MB}MB free on / - image updates need ~1.5GB transient headroom"
else
  # shadowsocks-only (or no containers at all): images are tiny
  (( AVAIL_MB >= 512 )) \
    || die "Only ${AVAIL_MB}MB free on / - need at least 512MB."
fi

TZ_VAL=$(timedatectl show -p Timezone --value 2>/dev/null) || TZ_VAL=
[[ -n ${TZ_VAL} ]] || TZ_VAL=Etc/UTC
log "Timezone: ${TZ_VAL}"

#--- AVX check -> MongoDB tag (Omada is 6.2 either way) ---------------------
if (( ENABLE_MONGO )); then
  if grep -qw avx /proc/cpuinfo; then
    MONGO_TAG=8.0
    log "AVX present: shared MongoDB ${MONGO_TAG}"
  else
    MONGO_TAG=4.4
    log "No AVX: shared MongoDB ${MONGO_TAG} (last pre-AVX major)"
  fi
fi

#--- Packages ---------------------------------------------------------------
log "Installing podman + baseline packages"
dnf -y install podman container-selinux openssl \
  dnf-automatic NetworkManager-wifi nano net-tools rsync udisks2 \
  vim-enhanced wget iperf3 bash-completion \
  pciutils usbutils >/dev/null
if (( ENABLE_DNS )); then
  dnf -y install dnsmasq >/dev/null
fi

#--- Small-disk / eMMC hygiene ----------------------------------------------
log "Applying small-disk hygiene (kernel retention, journal cap, zram)"

# Keep at most 2 installed kernels (default is 3)
if grep -q '^installonly_limit=' /etc/dnf/dnf.conf; then
  sed -i 's/^installonly_limit=.*/installonly_limit=2/' /etc/dnf/dnf.conf
else
  echo 'installonly_limit=2' >> /etc/dnf/dnf.conf
fi

# Cap the persistent journal; uncomment Storage=volatile instead once logs
# are shipped off-box (kinder to eMMC endurance)
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/10-small-disk.conf <<EOF
[Journal]
SystemMaxUse=100M
#Storage=volatile
EOF
systemctl restart systemd-journald

# Images are pinned - make sure auto-update machinery from earlier runs of
# this script is off, and drop its prune hook if present
systemctl disable --now podman-auto-update.timer >/dev/null 2>&1 || true
rm -f /etc/systemd/system/podman-auto-update.service.d/10-prune.conf

# zram swap instead of a disk swap partition (2GB RAM, eMMC endurance).
# Sized to full RAM (default is ram/2): both JVMs + mongod overcommit 2GB,
# so swap capacity matters more than the compressed-pages RAM cost.
if dnf -y install zram-generator-defaults >/dev/null 2>&1; then
  cat > /etc/systemd/zram-generator.conf <<EOF
[zram0]
zram-size = ram
compression-algorithm = zstd
EOF
  cat > /etc/sysctl.d/99-zram.conf <<EOF
# zram-friendly paging: push cold anon pages to compressed RAM early
vm.swappiness = 180
vm.page-cluster = 0
EOF
  sysctl -q --system >/dev/null
  systemctl daemon-reload
  if [[ -e /dev/zram0 ]]; then
    warn "zram0 already active - new size takes effect on next boot"
  else
    systemctl start systemd-zram-setup@zram0.service 2>/dev/null \
      || warn "zram will activate on next boot"
  fi
else
  warn "zram-generator-defaults not available - skipping zram setup"
fi

# Reclaim most of ext4's default 5% root reserve; enable periodic TRIM
ROOT_DEV=$(findmnt -n -o SOURCE /)
if [[ $(findmnt -n -o FSTYPE /) == ext4 ]]; then
  tune2fs -m 1 "${ROOT_DEV}" >/dev/null
  log "ext4 root reserve set to 1% on ${ROOT_DEV}"
else
  warn "root is not ext4 - skipping tune2fs root-reserve trim"
fi
systemctl enable --now fstrim.timer >/dev/null 2>&1 \
  || warn "could not enable fstrim.timer"

dnf clean all >/dev/null

#--- Automatic OS updates (dnf-automatic) -----------------------------------
log "Configuring dnf-automatic (apply updates, reboot when needed)"
set_automatic() {
  # Set key = value under [commands], replacing an existing line or
  # inserting after the section header. Idempotent; preserves comments.
  local key=$1 val=$2 f=/etc/dnf/automatic.conf
  if grep -qE "^${key}[[:space:]]*=" "${f}"; then
    sed -i -E "s/^${key}[[:space:]]*=.*/${key} = ${val}/" "${f}"
  else
    sed -i "/^\[commands\]/a ${key} = ${val}" "${f}"
  fi
  grep -q "^${key} = ${val}$" "${f}" \
    || die "Could not set ${key} in ${f}"
}
set_automatic apply_updates yes
set_automatic reboot when-needed
systemctl enable --now dnf-automatic.timer >/dev/null 2>&1 \
  || die "could not enable dnf-automatic.timer"

#--- Directories ------------------------------------------------------------
mkdir -p "${UNIFI_DIR}" "${QUADLET_DIR}"   # CRED_FILE lives in UNIFI_DIR on every box
if (( ENABLE_OMADA ));       then mkdir -p "${OMADA_DIR}"/{data,logs}; fi
if (( ENABLE_MONGO ));       then mkdir -p "${UNIFI_DIR}"/db; fi
if (( ENABLE_UNIFI ));       then mkdir -p "${UNIFI_DIR}"/config; fi
if (( ENABLE_SHADOWSOCKS )); then mkdir -p "${SS_DIR}"; fi

#--- Credentials (generated once, reused on re-run) -------------------------
if [[ ! -f ${CRED_FILE} ]]; then
  log "Generating credentials -> ${CRED_FILE}"
  install -m 600 /dev/null "${CRED_FILE}"
  {
    echo "MONGO_ROOT_PASS=$(openssl rand -hex 24)"
    echo "MONGO_UNIFI_PASS=$(openssl rand -hex 24)"
    echo "MONGO_OMADA_PASS=$(openssl rand -hex 24)"
    echo "SS_PASSWORD=$(openssl rand -base64 32)"
  } > "${CRED_FILE}"
else
  log "Reusing credentials from ${CRED_FILE}"
fi
# SS_PASSWORD was added after the mongo passwords; append if absent
grep -q '^SS_PASSWORD=' "${CRED_FILE}" \
  || echo "SS_PASSWORD=$(openssl rand -base64 32)" >> "${CRED_FILE}"
# shellcheck source=/dev/null
source "${CRED_FILE}"
[[ -n ${MONGO_ROOT_PASS:-} && -n ${MONGO_UNIFI_PASS:-} && -n ${MONGO_OMADA_PASS:-} && -n ${SS_PASSWORD:-} ]] \
  || die "${CRED_FILE} is missing one of MONGO_ROOT_PASS / MONGO_UNIFI_PASS / MONGO_OMADA_PASS / SS_PASSWORD"

# Secret-bearing env vars go into root-only files referenced from the
# quadlets via EnvironmentFile= - quadlet Environment= would end up on
# podman run's world-readable /proc/<pid>/cmdline
if (( ENABLE_MONGO )); then
  install -m 600 /dev/null "${UNIFI_DIR}/unifi-db.env"
  cat > "${UNIFI_DIR}/unifi-db.env" <<EOF
MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
MONGO_PASS=${MONGO_UNIFI_PASS}
MONGO_OMADA_PASS=${MONGO_OMADA_PASS}
EOF
fi
if (( ENABLE_UNIFI )); then
  install -m 600 /dev/null "${UNIFI_DIR}/unifi.env"
  cat > "${UNIFI_DIR}/unifi.env" <<EOF
MONGO_PASS=${MONGO_UNIFI_PASS}
EOF
fi
if (( ENABLE_OMADA )); then
  install -m 600 /dev/null "${OMADA_DIR}/omada.env"
  cat > "${OMADA_DIR}/omada.env" <<EOF
EAP_MONGOD_URI=mongodb://omada:${MONGO_OMADA_PASS}@unifi-db:27017/omada
EOF
fi

#--- Mongo first-run init script (runs only against an empty /data/db) ------
# Both app users are always created, whichever controllers are enabled, so
# the db looks identical on every box (and enabling the other app later
# never needs a db re-init).
if (( ENABLE_MONGO )); then
cat > "${UNIFI_DIR}/init-mongo.sh" <<'EOS'
#!/bin/bash
if which mongosh > /dev/null 2>&1; then
  mongo_init_bin='mongosh'
else
  mongo_init_bin='mongo'
fi
"${mongo_init_bin}" <<EOF
use ${MONGO_AUTHSOURCE}
db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
// unifi user lives in admin (app auths with MONGO_AUTHSOURCE=admin);
// created here in the current (admin) context, per upstream linuxserver.io
db.createUser({
  user: "${MONGO_USER}",
  pwd: "${MONGO_PASS}",
  roles: [
    { role: "dbOwner", db: "${MONGO_DBNAME}" },
    { role: "dbOwner", db: "${MONGO_DBNAME}_stat" },
    { role: "dbOwner", db: "${MONGO_DBNAME}_audit" }
  ]
})
// omada user lives in the omada db itself (its URI authSource is /omada);
// roles mirror mbentley's canonical omada.js: v6 uses omada AND omada_data
db.getSiblingDB("omada").createUser({
  user: "omada",
  pwd: "${MONGO_OMADA_PASS}",
  roles: [
    { role: "readWrite", db: "omada" },
    { role: "dbOwner",   db: "omada" },
    { role: "readWrite", db: "omada_data" },
    { role: "dbOwner",   db: "omada_data" }
  ]
})
EOF
EOS
chmod 755 "${UNIFI_DIR}/init-mongo.sh"
fi

#--- Quadlet: shared network ------------------------------------------------
if (( ENABLE_MONGO )); then
log "Writing ${QUADLET_DIR}/unifi.network"
cat > "${QUADLET_DIR}/unifi.network" <<EOF
# Shared by unifi-db, unifi, and omada
[Network]
NetworkName=unifi
EOF
fi

#--- Quadlet: shared MongoDB ------------------------------------------------
if (( ENABLE_MONGO )); then
log "Writing ${QUADLET_DIR}/unifi-db.container"
cat > "${QUADLET_DIR}/unifi-db.container" <<EOF
[Unit]
Description=Shared MongoDB (UniFi + Omada)

[Container]
Image=docker.io/mongo:${MONGO_TAG}
ContainerName=unifi-db
Network=unifi.network
Exec=--wiredTigerCacheSizeGB ${MONGO_CACHE_GB}
Volume=${UNIFI_DIR}/db:/data/db:Z
Volume=${UNIFI_DIR}/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro,Z
Environment=MONGO_INITDB_ROOT_USERNAME=root
Environment=MONGO_USER=unifi
Environment=MONGO_DBNAME=unifi
Environment=MONGO_AUTHSOURCE=admin
EnvironmentFile=${UNIFI_DIR}/unifi-db.env
# Dependents wait for a mongod that actually answers, not just a spawned
# container; generous start window covers post-crash repair on slow eMMC
Notify=healthy
HealthCmd=sh -c 'mongosh --quiet --eval "db.adminCommand({ping:1})" || mongo --quiet --eval "db.adminCommand({ping:1})"'
HealthStartPeriod=120s
# mongod gets podman's 10s SIGKILL by default - let it flush cleanly
PodmanArgs=--stop-timeout=60

[Service]
Restart=on-failure
TimeoutStartSec=900
TimeoutStopSec=90

[Install]
WantedBy=multi-user.target
EOF
chmod 600 "${QUADLET_DIR}/unifi-db.container"
fi

#--- Quadlet: Omada Controller 6.2 (external Mongo) -------------------------
if (( ENABLE_OMADA )); then
log "Writing ${QUADLET_DIR}/omada.container"
cat > "${QUADLET_DIR}/omada.container" <<EOF
[Unit]
Description=Omada Controller (external MongoDB)
Requires=unifi-db.service
After=unifi-db.service

[Container]
Image=${OMADA_IMAGE}
Network=unifi.network
Environment=TZ=${TZ_VAL}
Environment=MONGO_EXTERNAL=true
EnvironmentFile=${OMADA_DIR}/omada.env
Environment=PORTAL_HTTPS_PORT=8844
Environment=JAVA_MAX_HEAP_SIZE=${OMADA_HEAP_MAX}
Environment=JAVA_MIN_HEAP_SIZE=${OMADA_HEAP_MIN}
Volume=${OMADA_DIR}/data:/opt/tplink/EAPController/data:Z
Volume=${OMADA_DIR}/logs:/opt/tplink/EAPController/logs:Z
PublishPort=8088:8088
PublishPort=8043:8043
PublishPort=8844:8844
PublishPort=19810:19810/udp
PublishPort=27001:27001/udp
PublishPort=29810:29810/udp
PublishPort=29811-29817:29811-29817
PodmanArgs=--stop-timeout=60 --ulimit nofile=4096:8192

[Service]
Restart=on-failure
TimeoutStartSec=900
TimeoutStopSec=90

[Install]
WantedBy=multi-user.target
EOF
chmod 600 "${QUADLET_DIR}/omada.container"
fi

#--- Quadlet: UniFi Network Application -------------------------------------
if (( ENABLE_UNIFI )); then
log "Writing ${QUADLET_DIR}/unifi.container"
cat > "${QUADLET_DIR}/unifi.container" <<EOF
[Unit]
Description=UniFi Network Application
Requires=unifi-db.service
After=unifi-db.service

[Container]
Image=${UNIFI_IMAGE}
Network=unifi.network
Environment=PUID=1000
Environment=PGID=1000
Environment=TZ=${TZ_VAL}
Environment=MONGO_HOST=unifi-db
Environment=MONGO_PORT=27017
Environment=MONGO_USER=unifi
EnvironmentFile=${UNIFI_DIR}/unifi.env
Environment=MONGO_DBNAME=unifi
Environment=MONGO_AUTHSOURCE=admin
Environment=MEM_LIMIT=${UNIFI_MEM_LIMIT}
Volume=${UNIFI_DIR}/config:/config:Z
PublishPort=8443:8443
PublishPort=8080:8080
PublishPort=3478:3478/udp
PublishPort=10001:10001/udp
PodmanArgs=--stop-timeout=60

[Service]
Restart=on-failure
TimeoutStartSec=900
TimeoutStopSec=90

[Install]
WantedBy=multi-user.target
EOF
chmod 600 "${QUADLET_DIR}/unifi.container"
fi

#--- shadowsocks-rust: config + quadlet -------------------------------------
if (( ENABLE_SHADOWSOCKS )); then
log "Writing ${SS_DIR}/config.json"
install -m 600 /dev/null "${SS_DIR}/config.json"
cat > "${SS_DIR}/config.json" <<EOF
{
    "server": "0.0.0.0",
    "server_port": ${SS_PORT},
    "method": "2022-blake3-aes-256-gcm",
    "password": "${SS_PASSWORD}",
    "mode": "tcp_and_udp"
}
EOF

log "Writing ${QUADLET_DIR}/shadowsocks.container"
cat > "${QUADLET_DIR}/shadowsocks.container" <<EOF
[Unit]
Description=shadowsocks-rust server

[Container]
Image=${SS_IMAGE}
ContainerName=shadowsocks
Volume=${SS_DIR}/config.json:/etc/shadowsocks-rust/config.json:ro,Z
PublishPort=${SS_PORT}:${SS_PORT}
PublishPort=${SS_PORT}:${SS_PORT}/udp

[Service]
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
fi

#--- dnsmasq: LAN DNS (no DHCP) + hagezi pro blocklist ----------------------
if (( ENABLE_DNS )); then
log "Configuring dnsmasq (DNS only, hagezi pro blocklist)"

# systemd-resolved's 127.0.0.53 stub would EADDRINUSE dnsmasq's wildcard
# bind on port 53. EL ships plain NetworkManager resolv.conf, but handle a
# resolved-enabled host anyway: drop only the stub listener, keep resolved
# itself for the host, and repoint resolv.conf off the (now dead) stub.
if systemctl is-active --quiet systemd-resolved; then
  mkdir -p /etc/systemd/resolved.conf.d
  cat > /etc/systemd/resolved.conf.d/10-no-stub-listener.conf <<EOF
[Resolve]
DNSStubListener=no
EOF
  if [[ $(readlink -f /etc/resolv.conf 2>/dev/null) == /run/systemd/resolve/stub-resolv.conf ]]; then
    ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  fi
  systemctl restart systemd-resolved
fi

# Fedora/EL enable conf-dir in the stock dnsmasq.conf; make sure of it
grep -Eq '^[[:space:]]*conf-dir=/etc/dnsmasq\.d' /etc/dnsmasq.conf \
  || echo 'conf-dir=/etc/dnsmasq.d' >> /etc/dnsmasq.conf

cat > /etc/dnsmasq.d/lan-dns.conf <<EOF
# LAN resolver - written by setup-fedora-controllers.sh; edits are overwritten.
# DNS only: no dhcp-range is configured anywhere, so the DHCP/TFTP engine
# never activates (the router keeps doing DHCP).

# Don't forward plain names or RFC1918 reverse lookups upstream
domain-needed
bogus-priv

# Answer only hosts on directly attached subnets - a LAN resolver, not open
local-service

# Upstreams: Cloudflare + Google, IPv4 + IPv6; never read /etc/resolv.conf.
# dnsmasq favours whichever of these is answering.
no-resolv
server=1.1.1.1
server=1.0.0.1
server=2606:4700:4700::1111
server=2606:4700:4700::1001
server=8.8.8.8
server=8.8.4.4
server=2001:4860:4860::8888
server=2001:4860:4860::8844

# The default cache is a useless 150 entries; 10k costs about 1MB
cache-size=10000

# No log-queries: eMMC endurance. The hagezi pro list itself lives in
# ${HAGEZI_CONF} (~220k domains, ~50MB dnsmasq RSS -
# accepted on the 2GB box) and is refreshed by hagezi-update.timer.
EOF

log "Writing ${DNS_UPDATE_SCRIPT}"
{
cat <<EOF
#!/usr/bin/env bash
# Refresh the hagezi pro dnsmasq blocklist.
# Written by setup-fedora-controllers.sh; run daily by hagezi-update.timer.
set -euo pipefail
URL="${HAGEZI_URL}"
DEST="${HAGEZI_CONF}"
# The real list is ~220k lines; a low floor still catches error pages,
# truncated downloads, and redirects to HTML
MIN_LINES=10000
EOF
cat <<'EOF'
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
curl -fsSL --connect-timeout 30 --max-time 300 -o "$tmp" "$URL"
lines=$(wc -l < "$tmp")
(( lines >= MIN_LINES )) || { echo "refusing ${lines}-line download (< ${MIN_LINES})" >&2; exit 1; }
# The list must never be able to take dnsmasq down: syntax-check it alone
dnsmasq --test --conf-file="$tmp" >/dev/null 2>&1 \
  || { echo "downloaded list fails dnsmasq --test" >&2; exit 1; }
if [[ -f $DEST ]] && cmp -s "$tmp" "$DEST"; then
  echo "blocklist unchanged (${lines} lines)"
  exit 0
fi
[[ -f $DEST ]] && cp -p "$DEST" "$DEST.old"
# install(1), not mv: a fresh copy under /etc gets the right SELinux label
# (a file moved out of /tmp keeps user_tmp_t and dnsmasq can't read it)
install -m 644 "$tmp" "$DEST"
# SIGHUP does not re-read conf files - only a restart applies the new list
if systemctl is-active --quiet dnsmasq.service; then
  if ! systemctl restart dnsmasq.service; then
    echo "dnsmasq restart failed - rolling back to previous list" >&2
    [[ -f $DEST.old ]] && install -m 644 "$DEST.old" "$DEST"
    systemctl restart dnsmasq.service
    exit 1
  fi
fi
echo "installed ${lines}-line blocklist"
EOF
} > "${DNS_UPDATE_SCRIPT}"
chmod 755 "${DNS_UPDATE_SCRIPT}"

cat > /etc/systemd/system/hagezi-update.service <<EOF
[Unit]
Description=Refresh hagezi pro dnsmasq blocklist
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=${DNS_UPDATE_SCRIPT}
EOF

cat > /etc/systemd/system/hagezi-update.timer <<EOF
[Unit]
Description=Daily hagezi pro blocklist refresh

[Timer]
OnCalendar=daily
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
EOF

# Optional lancache steering. dnsmasq answers lancache.steamcontent.com
# (the single hostname modern Steam probes for cache discovery - the whole
# uklans/cache-domains steam.txt) with the cache IP; the address= entry
# also gives AAAA a NODATA answer, closing the IPv6 bypass. dnsmasq can't
# health-check, so a minutely timer probes the cache and toggles the
# override file: cache down -> file removed -> Steam resolves through the
# normal upstreams straight to the real CDN.
if [[ -n ${LANCACHE_IP} ]]; then
log "Writing ${LANCACHE_TOGGLE} (cache at ${LANCACHE_IP})"
{
cat <<EOF
#!/usr/bin/env bash
# Steer Steam at the local lancache while it is healthy; fall back to
# normal upstream resolution while it is not.
# Written by setup-fedora-controllers.sh; run minutely by lancache-watch.timer.
set -euo pipefail
CACHE_IP="${LANCACHE_IP}"
CONF="${LANCACHE_CONF}"
STATE=/run/lancache-dns.state
# Consecutive failed probes before falling back (hysteresis vs one lost probe)
FAIL_LIMIT=2
EOF
cat <<'EOF'
if curl -sf -o /dev/null --max-time 3 "http://${CACHE_IP}/lancache-heartbeat"; then
  fails=0
else
  fails=$(( $(cat "$STATE" 2>/dev/null || echo 0) + 1 ))
fi
echo "$fails" > "$STATE"

want="address=/lancache.steamcontent.com/${CACHE_IP}"
if (( fails == 0 )); then
  # Content check, not just existence: heals a stale IP after --lancache moves
  if [[ ! -f $CONF ]] || [[ $(<"$CONF") != "$want" ]]; then
    printf '%s\n' "$want" > "$CONF"
    systemctl try-restart dnsmasq.service
    echo "lancache healthy - Steam steering enabled"
  fi
elif (( fails >= FAIL_LIMIT )) && [[ -f $CONF ]]; then
  rm -f "$CONF"
  systemctl try-restart dnsmasq.service
  echo "lancache unreachable (${fails} probes) - falling back to upstream DNS"
fi
EOF
} > "${LANCACHE_TOGGLE}"
chmod 755 "${LANCACHE_TOGGLE}"

cat > /etc/systemd/system/lancache-watch.service <<EOF
[Unit]
Description=Probe lancache and toggle dnsmasq Steam steering

[Service]
Type=oneshot
ExecStart=${LANCACHE_TOGGLE}
EOF

cat > /etc/systemd/system/lancache-watch.timer <<EOF
[Unit]
Description=Minutely lancache health probe

[Timer]
OnBootSec=30s
OnUnitActiveSec=1min
AccuracySec=15s

[Install]
WantedBy=timers.target
EOF
fi
fi

#--- Disabled components: stop them, drop their quadlets (data is kept) -----
# Makes flag flips converge on re-run; stop happens while the generated
# unit still exists (before the daemon-reload below removes it)
if (( ! ENABLE_UNIFI )); then
  systemctl stop unifi.service 2>/dev/null || true
  rm -f "${QUADLET_DIR}/unifi.container" "${UNIFI_DIR}/unifi.env"
fi
if (( ! ENABLE_OMADA )); then
  systemctl stop omada.service 2>/dev/null || true
  rm -f "${QUADLET_DIR}/omada.container" "${OMADA_DIR}/omada.env"
fi
if (( ! ENABLE_SHADOWSOCKS )); then
  systemctl stop shadowsocks.service 2>/dev/null || true
  rm -f "${QUADLET_DIR}/shadowsocks.container"
fi
if (( ! ENABLE_MONGO )); then
  systemctl stop unifi-db.service 2>/dev/null || true
  rm -f "${QUADLET_DIR}/unifi-db.container" "${QUADLET_DIR}/unifi.network" \
        "${UNIFI_DIR}/unifi-db.env" "${UNIFI_DIR}/init-mongo.sh"
fi
if (( ! ENABLE_DNS )); then
  systemctl disable --now hagezi-update.timer lancache-watch.timer 2>/dev/null || true
  systemctl disable --now dnsmasq.service 2>/dev/null || true
  rm -f /etc/dnsmasq.d/lan-dns.conf "${HAGEZI_CONF}" "${HAGEZI_CONF}.old" \
        "${LANCACHE_CONF}" "${DNS_UPDATE_SCRIPT}" "${LANCACHE_TOGGLE}" \
        /run/lancache-dns.state \
        /etc/systemd/system/hagezi-update.{service,timer} \
        /etc/systemd/system/lancache-watch.{service,timer}
  # /etc/systemd/resolved.conf.d/10-no-stub-listener.conf is left alone -
  # restoring the stub could break host resolution mid-run
elif [[ -z ${LANCACHE_IP} ]]; then
  # dns on, lancache off: drop just the steering pieces; the dnsmasq restart
  # in the start section below picks up the removed override
  systemctl disable --now lancache-watch.timer 2>/dev/null || true
  rm -f "${LANCACHE_CONF}" "${LANCACHE_TOGGLE}" /run/lancache-dns.state \
        /etc/systemd/system/lancache-watch.{service,timer}
fi

#--- Firewall ---------------------------------------------------------------
if systemctl is-active --quiet firewalld; then
  log "Opening firewalld ports"
  if (( ENABLE_OMADA )); then
    firewall-cmd -q --permanent --add-port={8043,8088,8844}/tcp
    firewall-cmd -q --permanent --add-port=29811-29817/tcp
    firewall-cmd -q --permanent --add-port={19810,27001,29810}/udp
  fi
  if (( ENABLE_UNIFI )); then
    firewall-cmd -q --permanent --add-port={8443,8080}/tcp
    firewall-cmd -q --permanent --add-port={3478,10001}/udp
  fi
  if (( ENABLE_SHADOWSOCKS )); then
    firewall-cmd -q --permanent --add-port="${SS_PORT}/tcp" --add-port="${SS_PORT}/udp"
  fi
  if (( ENABLE_DNS )); then
    firewall-cmd -q --permanent --add-port=53/tcp --add-port=53/udp
  fi
  firewall-cmd -q --reload
else
  warn "firewalld not active - skipping firewall rules"
fi

#--- Pull images (once - images are pinned, re-runs never re-pull) ----------
IMAGES=()
if (( ENABLE_MONGO ));       then IMAGES+=("docker.io/mongo:${MONGO_TAG}"); fi
if (( ENABLE_OMADA ));       then IMAGES+=("${OMADA_IMAGE}"); fi
if (( ENABLE_UNIFI ));       then IMAGES+=("${UNIFI_IMAGE}"); fi
if (( ENABLE_SHADOWSOCKS )); then IMAGES+=("${SS_IMAGE}"); fi
for img in "${IMAGES[@]}"; do
  if podman image exists "${img}"; then
    log "Image present (pinned): ${img}"
  else
    log "Pulling ${img}"
    podman pull -q "${img}" >/dev/null
  fi
done

#--- Generate units and start -----------------------------------------------
SERVICES=()
if (( ENABLE_MONGO ));       then SERVICES+=(unifi-db); fi
if (( ENABLE_OMADA ));       then SERVICES+=(omada); fi
if (( ENABLE_UNIFI ));       then SERVICES+=(unifi); fi
if (( ENABLE_SHADOWSOCKS )); then SERVICES+=(shadowsocks); fi

log "Reloading systemd (quadlet generation)"
systemctl daemon-reload
for u in "${SERVICES[@]}"; do
  systemctl cat "${u}.service" >/dev/null 2>&1 \
    || die "Quadlet generation failed for ${u}.service. Debug with: /usr/lib/systemd/system-generators/podman-system-generator --dryrun"
done

# Stop-then-start (rather than plain start) so re-runs apply config changes
systemctl stop unifi.service omada.service shadowsocks.service unifi-db.service 2>/dev/null || true

if (( ENABLE_MONGO )); then
# Notify=healthy in the quadlet: start blocks until mongod answers ping
systemctl start unifi-db.service

# The healthcheck can also be satisfied by the entrypoint's temporary
# first-init instance. Require real auth + both app users before starting
# the apps, so a half-initialized db fails HERE with a clear remedy instead
# of as an app-side auth crash-loop.
log "Verifying MongoDB auth and app users"
mongo_user_count() {
  podman exec -i unifi-db sh -c \
    'command -v mongosh >/dev/null 2>&1 && exec mongosh --quiet || exec mongo --quiet' 2>/dev/null <<EOF
try {
  db.getSiblingDB("admin").auth("root", "${MONGO_ROOT_PASS}")
  // all users live in admin.system.users; the db field is their authSource
  print("USERS=" + (db.getSiblingDB("admin").system.users.countDocuments({user:"unifi", db:"admin"}) +
                    db.getSiblingDB("admin").system.users.countDocuments({user:"omada", db:"omada"})))
} catch (e) { print("USERS=ERR") }
EOF
}
t=0
until mongo_user_count | grep '^USERS=2$' >/dev/null; do
  sleep 2; t=$(( t + 2 ))
  (( t >= 180 )) && die "MongoDB app users not present after 180s. If the very first init was interrupted, the db is half-initialized: systemctl stop unifi-db, wipe ${UNIFI_DIR}/db, and re-run."
done
log "MongoDB ready (unifi + omada users present)"
fi

if (( ENABLE_DNS )); then
  log "Starting dnsmasq"
  systemctl enable dnsmasq.service >/dev/null 2>&1 \
    || die "could not enable dnsmasq.service"
  # Initial pull; non-fatal - dnsmasq runs unfiltered until the timer catches up
  systemctl start hagezi-update.service \
    || warn "initial hagezi pull failed - dnsmasq starts without the blocklist (hagezi-update.timer retries daily)"
  systemctl enable --now hagezi-update.timer >/dev/null 2>&1 \
    || die "could not enable hagezi-update.timer"
  # Restart (not just start) so re-runs apply config changes, like the containers
  systemctl restart dnsmasq.service
  if [[ -n ${LANCACHE_IP} ]]; then
    systemctl enable --now lancache-watch.timer >/dev/null 2>&1 \
      || die "could not enable lancache-watch.timer"
    # One immediate probe so the steering state is correct right now
    systemctl start lancache-watch.service
  fi
fi

wait_for() {
  local name=$1 url=$2 timeout=${3:-420} t=0
  until curl -skf -o /dev/null --max-time 5 "${url}"; do
    t=$(( t + 5 ))
    if (( t >= timeout )); then
      warn "${name} not answering at ${url} after ${timeout}s (may still be initializing; check journalctl -eu)"
      return 0
    fi
    sleep 5
  done
  log "${name} is up: ${url}"
}

# Start the JVM apps one at a time - concurrent first-runs of two JVMs
# overcommit 2GB hard (first boot on this hardware can take several minutes)
if (( ENABLE_UNIFI )); then
  log "Starting unifi"
  systemctl start unifi.service
  wait_for "UniFi" https://localhost:8443
fi
if (( ENABLE_OMADA )); then
  log "Starting omada"
  systemctl start omada.service
  wait_for "Omada" https://localhost:8043
fi
if (( ENABLE_SHADOWSOCKS )); then
  log "Starting shadowsocks"
  systemctl start shadowsocks.service
fi

#--- Verify boot enablement -------------------------------------------------
# Quadlet units are enabled via their [Install] WantedBy at generation time;
# 'systemctl enable' does not apply to generated units.
for u in "${SERVICES[@]}"; do
  if [[ -e /run/systemd/generator/multi-user.target.wants/${u}.service ]]; then
    log "${u}.service: will start at boot (multi-user.target.wants)"
  else
    warn "${u}.service not linked into multi-user.target.wants - check its [Install] section"
  fi
done

#--- Verify runtime ---------------------------------------------------------
for u in "${SERVICES[@]}"; do
  systemctl is-active --quiet "${u}.service" \
    || die "${u}.service is not active. See: journalctl -eu ${u}.service"
done
if (( ENABLE_DNS )); then
  systemctl is-active --quiet dnsmasq.service \
    || die "dnsmasq.service is not active. See: journalctl -eu dnsmasq.service"
fi
if (( ${#SERVICES[@]} )); then
  log "All services active"
else
  log "No containers enabled - host baseline configured"
fi

# Retire superseded omada images (e.g. after the 6.2 -> 6.2-openj9 swap):
# still-tagged old images survive `podman image prune`, and 8GB can't
# spare the ~700MB. Data is unaffected - it lives in ${OMADA_DIR} volumes
# and the external MongoDB, not in the image.
if (( ENABLE_OMADA )); then
  podman images --format '{{.Repository}}:{{.Tag}}' docker.io/mbentley/omada-controller 2>/dev/null \
    | grep -vxF "${OMADA_IMAGE}" | xargs -r podman rmi >/dev/null 2>&1 \
    || true
fi

#--- Summary ----------------------------------------------------------------
# hostname -I can lead with the podman bridge IP; prefer the route source
HOST_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.*src \([0-9.]*\).*/\1/p' || true)
[[ -n ${HOST_IP} ]] || HOST_IP=$(hostname -I | awk '{print $1}')

DATA_DIRS=${UNIFI_DIR}
if (( ENABLE_OMADA ));       then DATA_DIRS+=", ${OMADA_DIR}"; fi
if (( ENABLE_SHADOWSOCKS )); then DATA_DIRS+=", ${SS_DIR}"; fi

cat <<EOF

============================================================
 Done. Components: omada=${ENABLE_OMADA} unifi=${ENABLE_UNIFI} mongodb=${ENABLE_MONGO} shadowsocks=${ENABLE_SHADOWSOCKS} dns=${ENABLE_DNS} lancache=${LANCACHE_IP:-off}

EOF
if (( ENABLE_OMADA )); then
  echo " Omada 6.2 OpenJ9 : https://${HOST_IP}:8043   (portal on 8844)"
fi
if (( ENABLE_UNIFI )); then
  echo " UniFi Network    : https://${HOST_IP}:8443   (inform on 8080)"
fi
if (( ENABLE_MONGO )); then
  echo " Shared MongoDB   : mongo:${MONGO_TAG} in 'unifi-db' (dbs: unifi, omada)"
fi
if (( ENABLE_SHADOWSOCKS )); then
  echo " Shadowsocks      : ${HOST_IP}:${SS_PORT} tcp+udp, 2022-blake3-aes-256-gcm"
  echo "                    (key = SS_PASSWORD in the credentials file)"
fi
if (( ENABLE_DNS )); then
  echo " LAN DNS          : ${HOST_IP}:53 tcp+udp - dnsmasq, DNS only (no DHCP)"
  echo "                    hagezi pro blocklist, refreshed daily (hagezi-update.timer)"
  echo "                    upstreams: Cloudflare + Google, IPv4 + IPv6"
  if [[ -n ${LANCACHE_IP} ]]; then
    if [[ -f ${LANCACHE_CONF} ]]; then
      echo "                    lancache: steering Steam -> ${LANCACHE_IP} (healthy)"
    else
      echo "                    lancache: ${LANCACHE_IP} not responding - direct upstream for now"
    fi
    echo "                    (lancache-watch.timer re-probes every minute)"
  fi
  echo "                    point the router's DHCP DNS option (opt 6) at ${HOST_IP}"
fi
cat <<EOF

 Credentials      : ${CRED_FILE} (mode 600)
 Quadlet units    : ${QUADLET_DIR} (one .container per enabled component)
 Data             : ${DATA_DIRS}
 Images           : PINNED - nothing auto-updates or re-pulls. To update:
                    podman pull <image> && systemctl restart <svc>, then
                    podman image prune -f. Before updating unifi, confirm
                    the new version still supports MongoDB 4.4.
 Disk hygiene     : superseded-image cleanup, installonly_limit=2,
                    journal capped at 100M, zram swap = RAM (no disk swap),
                    ext4 reserve at 1%, fstrim.timer on
 OS updates       : dnf-automatic daily (apply_updates=yes, reboot=when-needed)
EOF
if (( ENABLE_MONGO )); then
  echo
  echo " Post-setup checklist (in the UIs):"
  if (( ENABLE_UNIFI )); then
    echo "   - UniFi: Settings > System > set statistics retention to minimum"
    echo "     (the stat db is the main disk-growth risk on 8GB)"
  fi
  echo "   - Controller UIs: enable auto-backup; rsync the backups off-box"
  echo "   - Keep an eye on df -h / before manual image updates (~1.5GB headroom)"
  echo
  echo " Controller UIs run a first-time setup wizard. Adoption is L3-only"
  echo " (discovery broadcasts do not cross the podman bridge):"
  if (( ENABLE_UNIFI )); then
    echo "   UniFi devices : set-inform http://${HOST_IP}:8080/inform (or DHCP opt 43)"
  fi
  if (( ENABLE_OMADA )); then
    echo "   Omada devices : controller IP ${HOST_IP} (or DHCP opt 138)"
  fi
fi
echo "============================================================"
